config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
  end
  root 'items#index'

  resources :items do
    member do
      get 'purchase', to: 'items#purchase'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
    collection do
      get 'search', to: 'items#search'
    end
  end
  resources :users do
    member do
      get 'profile', to: 'users#profile'
      get 'credit', to: 'users#credit'
      get 'logout', to: 'users#logout'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/views/shared/_aside.html.haml
.aside
  .aside__box
    .inner
      .inner-left
        .upper-text スマホでかんたんフリマアプリ
        .lower-text 今すぐ無料ダウンロード!
        .icons
          %img{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?3856598694", width: 68, class: "icons__icon"}
          %ul.btn
            %li.btn__apple
              = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&amp;mt=8" do
                %img{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3856598694", width: 133, height: 40}
            %li.btn__google
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&amp;hl=ja" do
                %img{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3856598694", width: 133, height: 40}

      %img{src:"//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?3856598694", class: "inner-right"}

app/views/shared/_bread-crumbs.html.haml
%nav.bread-crumbs
  %ul
    %li.itemScope
      =link_to('メルカリ','#')
      %i.fa.fa-chevron-right.fa-x
    %li.itemScope
      =link_to('マイページ','#')

app/views/shared/_child.html.haml
%li.child__name
  .child_box
    = link_to "#{child.name}", '#', class: "child-link"
    %ul.grandchild
      - child.children.each do |grandchild|
        %li= link_to grandchild.name, '#', class: "grandchild-link"

app/views/shared/_credit_form.html.haml
.pay-main
  .address-title
    %a.form-title 支払い方法
  .formGroup
    %label(for="zip_code") カード番号
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="zip_code" placeholder="半角数字のみ" class="input-default")
    %ul.signup-card-list
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3270184656")
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3270184656")
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3270184656")
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3270184656")
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3270184656")
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3270184656")
      %li.card-decoration
        = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3270184656")
    .formGroup-select
      %label(for="zip_code") 有効期限
      %span.form-arbitrary-required 必須
    .formGroup-select
      %select#payment_card_expire_mm.select-default
        %option{value: "01"} 01
        %option{value: "02"} 02
        %option{value: "03"} 03
        %option{value: "04"} 04
        %option{value: "05"} 05
        %option{value: "06"} 06
        %option{value: "07"} 07
        %option{value: "08"} 08
        %option{value: "09"} 09
        %option{value: "10"} 10
        %option{value: "11"} 11
        %option{value: "12"} 12
      %i.fa.fa-chevron-down.credit
      %span.credit-selectbox 月
    .formGroup-select.credit
      %select#payment_card_expire_yy.select-default
        %option{value: "19"} 19
        %option{value: "20"} 20
        %option{value: "21"} 21
        %option{value: "22"} 22
        %option{value: "23"} 23
        %option{value: "24"} 24
        %option{value: "25"} 25
        %option{value: "26"} 26
        %option{value: "27"} 27
        %option{value: "28"} 28
        %option{value: "29"} 29
      %i.fa.fa-chevron-down
      %span.credit-selectbox 年
  .formGroup
    %label(for="zip_code") セキュリティコード
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="zip_code" placeholder="カード背面4桁もしくは3桁の番号" class="input-default")
    .card-text
      = link_to "/jp/help_center/article/244/", target: "_blank" do
        %span.questionForm ?
        カード裏面の番号とは？
        %i.icon-arrow-right
  .formGroup
    %button(type="submit" class="btn")次へ進む

app/views/shared/_footer-btn.html.haml
.footer-sell-btn
  = link_to new_item_path do
    %div 出品
    = fa_icon 'camera',class: 'icon-camera'

app/views/shared/_footer.html.haml
.footer
  .footer__top.clearfix
    .cell
      .list__header メルカリについて
      %ul.link__list
        %li.link__text.first-child
          = link_to "https://about.mercari.com/" do
            会社概要（運営会社）
          
        %li.link__text
          = link_to "https://www.mercari.com/jp/jobs/" do
            採用情報

        %li.link__text
          = link_to "https://about.mercari.com/press/news/" do
            プレスリリース

        %li.link__text
          = link_to "https://jp-news.mercari.com/" do
            公式ブログ

        %li.link__text
          = link_to "https://www.mercari.com/jp/logo-guidelines/" do
            メルカリロゴ利用ガイドライン

        %li.link__icon
          = link_to "https://twitter.com/mercari_jp" do
            %i.fab.fa-twitter

        %li.link__icon
          = link_to "https://www.facebook.com/mercarijp" do
            %i.fab.fa-facebook-square

    .cell
      .list__header ヘルプ&ガイド
      %ul.link__list
        %li.link__text.first-child
          = link_to "https://www.mercari.com/jp/help_center/" do
            メルカリガイド

        %li.link__text
          = link_to "https://www.mercari.com/jp/rakuraku-mercari/" do
            らくらくメルカリ便

        %li.link__text
          = link_to "https://www.mercari.com/jp/yuyu-mercari/" do
            ゆうゆうメルカリ便

        %li.link__text
          = link_to "https://www.mercari.com/jp/rakuraku-ogata/" do
            大型メルカリ便

        %li.link__text
          = link_to "https://www.mercari.com/jp/guide/car/" do
            車体取引ガイド

        %li.link__text
          = link_to "https://www.mercari.com/jp/safe/description/" do
            メルカリあんしん・あんぜん宣言！

        %li.link__text
          = link_to "https://www.mercari.com/jp/authenticity/" do
            偽ブランド品撲滅への取り組み

        %li.link__text
          = link_to "https://www.mercari.com/jp/box/" do
            メルカリボックス

    .cell.full-width
      .list__header プライバシーと利用規約
      .inner-cell
        %ul.link__list
          %li.link__text.first-child
            = link_to "https://www.mercari.com/jp/privacy/" do
              プライバシーポリシー

          %li.link__text
            = link_to "https://www.mercari.com/jp/tos/" do
              メルカリ利用規約

          %li.link__text
            = link_to "https://www.mercari.com/jp/tos_smartphone_support/" do
              あんしんスマートサポート制度に関する利用規約

          %li.link__text
            = link_to "https://www.mercari.com/jp/compliance/" do
              コンプライアンスポリシー

      .inner-cell
        %ul.link__list
          %li.link__text.first-child
            = link_to "https://www.mercari.com/jp/data_security/" do
              個人データの安全管理に係る基本方針

          %li.link__text
            = link_to "https://www.mercari.com/jp/tokutei/" do
              特定商取引に関する表記

          %li.link__text
            = link_to "https://www.mercari.com/jp/shikin_kessai/" do
              資金決済法に基づく表示

          %li.link__text
            = link_to "https://about.mercari.com/csr/safety/" do
              法令順守と犯罪抑止のために

          %li.link__text
            = link_to "https://www.mercari.com/jp/help_center/category/458/" do
              返品・返金ポリシー

    .cell.right
      .list__header 国
      %ul.link__list
        %li.link__text.first-child
          = link_to "https://www.mercari.com/jp/" do
            日本

        %li.link__text
          = link_to "https://www.mercari.com/" do
            United States

  .footer__bottom
    = link_to "https://www.mercari.com/jp/",class: "logo" do
      %img{src:"//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?3856598694"}

    %span.copyright © 2019 Mercari

app/views/shared/_header.html.haml
.header
  .box 
    .box__top
      = link_to root_path do
        = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1107552019", class:"title") 
      = render 'shared/search_form'

    -# 各ボタンは一時的にトップページに遷移するように設定
    .box__bottom
      %ul.left
        %li.left-btn--category
          = link_to root_path do
            = fa_icon 'list',class: 'left-btn--category__icon'
            %span カテゴリーから探す
          .accordion
            %ul.parent
              = render partial: "shared/parent", collection: @parents

        %li.left-btn--brand
          = link_to root_path do
            = fa_icon 'tag',class: 'left-btn--brand__icon'
            %span ブランドから探す

      %ul.right
        %li.right-btn
          = link_to root_path do
            = fa_icon 'bell',class: 'right-btn__icon'
            %span お知らせ

        %li.right-btn
          = link_to root_path do
            = fa_icon 'check',class: 'right-btn__icon'
            %span やることリスト

        %li.right-btn
          = link_to user_path(current_user) do
            %img{src:"//static.mercdn.net/images/member_photo_noimage_thumb.png", width: 32, class:"right-btn__mypage-icon"}
            %span マイページ
            

app/views/shared/_item.html.haml
- if @item.errors.any?
  .flash_message
    = flash[:alert]
= render 'shared/sub-header'
.item-main
  .form
    = form_with(model:@item, local: true) do |f|
      .item-contents
        .item-contents__head
          .head__title
            %h2 商品の情報を入力
        .item-contents__image
          .image__head
            %h3 出品画像
            %span 必須
            %h5 最大１０枚までアップロードできます
          .image__box
            = f.label :images do
              #itemtext
                %p#itemtextP1 ドラッグアンドドロップ
                %p#itemtextP2 またはクリックしてファイルをダウンロード
              = f.file_field :images, multiple: true, class: 'hidden',onchange:"previewFiles()"
              .imageSelect
              #preview
        .item-contents__info
          .info__name
            %h4 商品名
            %span 必須
          .info__default
            = f.text_field :name, type:"text", placeholder:"商品名（必須４０文字まで）"
          .info__description
            .description__item
              %h4 商品の説明
              %span 必須
            .description__comment
              = f.text_area :discription, type:'text', placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",rows: "10",class: "textarea-default"
        #categoryAppend-size.item-contents__detail
          %h4 商品の詳細
          .detail__box
            .box__group
              %label
                %h3 カテゴリー
                %span 必須
              #categoryAppend.select__box
                = fields_for :items_categories do |items_categories|
                  = items_categories.select :category_id,Category.roots.map {|i| ["#{i.name}", i.id]},{prompt: "---"},{id:"form1"}
                %i.fa.fa-chevron-down
              #categoryAppend-1.select__box.hidden
                = fields_for :items_categories do |items_categories|
                  = items_categories.select :category_id,{},{prompt: "---"},{id:"form2"}
                %i.fa.fa-chevron-down
              #categoryAppend-2.select__box.hidden
                = f.fields_for :items_categories do |items_categories|
                  = items_categories.select :category_id,{},{prompt: "---"},{id:"form3"}
                %i.fa.fa-chevron-down
            #categoryAppend-sizeform.box__group1.hidden
              %label
                %h3 サイズ
                %span.any 任意
              .select__box
                = f.select :size, [["---","---"],["XXS以下","XXS以下"],["XS(SS)","XS(SS)"],["S","S"],["M","M"],["L","L"],["XL(LL)","XL(LL)"],["2XL(3L)","2XL(3L)"],["3XL(4L)","3XL(4L)"],["4XL(5L)以上","4XL(5L)以上"],["FREE SIZE","FREE SIZE"]], class:"select-default"
                %i.fa.fa-chevron-down
            #categoryAppend-any.box__group-any.hidden
              %label
                %h3 ブランド
                %span.any 任意
              .select__box
                = f.text_field :brand, class:"select-default", placeholder:"例）シャネル"
            .box__group1
              %h3 商品の状態
              %span 必須
              .select__box
                = f.select :item_condition, [["---","---"],["新品・未使用","新品・未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], class:"select-default"
                %i.fa.fa-chevron-down
        #a.item-contents__shipping
          %h4 配送について
          .form-question
            = link_to "？", "#", target: "_blank"
          .shipping__box
            .box__fee
              %h3 配送料の負担
              %span 必須  
              #delivery-fee.select__box
                = f.select :delivery_fee, [["---","---"],["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]], class:"select-default"
                %i.fa.fa-chevron-down
            #appendBox-rule.box__rule.hidden
              %h3 配送方法
              %span 必須  
              .select__box
                = f.select :shipping_rule, [["---","---"],["未定","未定"],["らくらくメルカリ便","らくらくメルカリ便"],["ゆうメール","ゆうメール"],["レターパック","レターパック"],["普通郵便(定型、定型外)","普通郵便(定型、定型外)"],["クロネコヤマト","クロネコヤマト"],["ゆうパック","ゆうパック"],["クリックポスト","クリックポスト"],["ゆうパケット","ゆうパケット"]], class:"select-default"
                %i.fa.fa-chevron-down
            .box__area
              %h3 発送元の地域
              %span 必須
              .select__box
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name
                %i.fa.fa-chevron-down
            .box__date
              %h3 発送までの日数
              %span 必須
              .select__box
                = f.select :shipping_date, [["---","---"],["１〜２日で発送","１〜２日で発送"],["２〜３日で発送","２〜３日で発送"],["４〜７日で発送","４〜７日で発送"]], class:"select-default"
                %i.fa.fa-chevron-down
        .item-contents__price
          %h4 販売価格(300〜9,999,999)
          .form-question
            = link_to "？", "#", target: "_blank"
          .price__box
            .list__top
              .top__left
                価格
                %span 必須
              .top__right
                .price__input
                  ￥
                  = f.text_field :price, type:"text", placeholder:"例）300", id: "price"
            .list__center
              .left
                販売手数料(10%)
                #fee-js
                  %p#fee- -
            .list__bottom
              %p.left 販売利益
              #profit-js
                %p.right#fee- -
        .item-contents__submit
          = link_to "禁止されている商品", "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
          = link_to "行為", "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
          を必ずご確認ください。
          %br またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to "偽ブランドの販売", "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
          は犯罪であり処罰される可能性があります。
          %br また、出品を持ちまして
          = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/"
          にも同意したことになります。
          %br
          .submit__buttom
            = f.submit '出品する', class: 'btn-default'
          .submit__last
            = link_to root_path do
              %button{type:"submit", class:"btn-default"}
                もどる
= render 'shared/sub-footer'

app/views/shared/_main.html.haml
.main
  .swiper
    .swiper-container
      .swiper-wrapper
        .swiper-slide
          %img{src: "images/slide1.jpg"}/
        .swiper-slide
          %img{src: "images/slide2.jpg"}/
        .swiper-slide
          %img{src: "images/slide3.jpg"}/
      .swiper-pagination
      .swiper-button-prev
      .swiper-button-next

  .pickup-box
    .head ピックアップカテゴリー
    .item-box__container.clearfix
      .text-center
        = link_to "#" do
          新着アイテム
      .item-box__content.clearfix
        .item-box
          = link_to item_path(Item.last.id) do
            .photo
              = image_tag(@items[0].images.first, class: "photo__img")
            .item
              .item__name
                = @items[0].name
              .item__num
                .item__price
                  ¥
                  = @items[0].price
              .item__tax (税込)

        .item-box
          = link_to item_path(Item.last(2).first.id) do
            .photo
              = image_tag(@items[1].images.first, class: "photo__img")

            .item
              .item__name
                = @items[1].name
              .item__num
                .item__price
                  ¥ 
                  = @items[1].price
              .item__tax (税込)

        .item-box
          = link_to item_path(Item.last(3).first.id) do
            .photo
              = image_tag(@items[2].images.first, class: "photo__img")

            .item
              .item__name
                = @items[2].name
              .item__num
                .item__price 
                  ¥ 
                  = @items[2].price
              .item__tax (税込)

        .item-box
          = link_to item_path(Item.last(4).first.id) do
            .photo
              = image_tag(@items[3].images.first, class: "photo__img")

            .item
              .item__name
                = @items[3].name
              .item__num
                .item__price
                  ¥ 
                  = @items[3].price
              .item__tax (税込)

      .view-all
        = link_to "/items/search?utf8=✓&q%5Bname_cont%5D=&button=" do
          全ての商品を見る

  .pickup-box
    .head ピックアップブランド
    .item-box__container.clearfix
      .text-center
        = link_to "#" do
          新着アイテム
      .item-box__content.clearfix
        .item-box
          = link_to item_path(@items2[0].id) do
            .photo
              = image_tag(@items2[0].images.first, class: "photo__img")
            .item
              .item__name
                = @items2[0].name
              .item__num
                .item__price
                  ¥ 
                  = @items2[0].price
              .item__tax (税込)

        .item-box
          = link_to item_path(@items2[1].id) do
            .photo
              = image_tag(@items2[1].images.first, class: "photo__img")
            .item
              .item__name

                = @items2[1].name
              .item__num
                .item__price
                  ¥
                  = @items2[1].price
              .item__tax (税込)

        .item-box
          = link_to item_path(@items2[2].id) do
            .photo
              = image_tag(@items2[2].images.first, class: "photo__img")

            .item
              .item__name
                = @items2[2].name
              .item__num
                .item__price 
                  ¥ 
                  = @items2[2].price
              .item__tax (税込)

        .item-box
          = link_to item_path(@items2[3].id) do
            .photo
              = image_tag(@items2[3].images.first, class: "photo__img")

            .item
              .item__name
                = @items2[3].name
              .item__num
                .item__price
                  ¥ 
                  = @items2[3].price
              .item__tax (税込)

      .view-all
        = link_to "/items/search?utf8=✓&q%5Bname_cont%5D=&button=" do
          全ての商品を見る
          

app/views/shared/_parent.html.haml
%li.parent__name
  .parent_box
    = link_to "#{parent.name}", '#', class: "parent-link"
    %ul.child
      = render partial: "shared/child", collection: parent.children

app/views/shared/_search_form.html.haml
- if @q != nil
    = search_form_for(@q, url:search_items_path) do |s|
        = s.search_field :name_cont, placeholder:"何かお探しですか？", class:"search-bar__box"
        = button_tag type:"submit", class:"search-bar__icon" do
            =fa_icon 'search lg'
- else
    redirect_to root_path

app/views/shared/_side_bar.html.haml
.side-bar
  %nav.mypageNav
    %ul.mypageNavList
      %li
        = link_to user_path(current_user),class:"mypageNavList__item" do
          マイページ
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          お知らせ
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          やることリスト
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          いいね！一覧
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          出品する
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          出品した商品-出品中
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          出品した商品-取引中
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          出品した商品-売却済み
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          購入した商品-取引中
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          購入した商品-過去の取引
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          ニュース一覧
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          評価一覧
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          ガイド
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          お問い合わせ
          %i.fa.fa-chevron-right
    %h3.mypageNavHead メルペイ
    %ul.mypageNavList
      %li
        %a.mypageNavList__item.active{href: "#"}
          売上・振込申請
          %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          ポイント
          %i.fa.fa-chevron-right
    %h3.mypageNavHead 設定
    %ul.mypageNavList
      %li
        .mypageNavList__item.active
          = link_to profile_user_path(current_user) do
            %span プロフィール
            %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          発送元・お届け先住所変更
          %i.fa.fa-chevron-right
      %li
        .mypageNavList__item.active
          = link_to credit_user_path(current_user) do
            %span 支払い方法
            %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          メール/パスワード
          %i.fa.fa-chevron-right
      %li
        .mypageNavList__item.active
          = link_to edit_user_path(current_user) do
            %span 本人情報
            %i.fa.fa-chevron-right
      %li
        %a.mypageNavList__item.active{href: "#"}
          電話番号の確認
          %i.fa.fa-chevron-right
      %li
        .mypageNavList__item.active
          = link_to logout_user_path(current_user) do
            %span ログアウト
            %i.fa.fa-chevron-right

app/views/shared/_sub-footer.html.haml
.sub-footer
  .box
    %ul.clearfix
      %a.link_left 
      = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"

      %a.link_center
      = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/" 
      
      %a.link_right
      = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"

    .single-footer-logo
      = link_to root_path do
        = image_tag('//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3856598694', alt: "mercari", src: "")
      %p
        %small © 2019 Mercari

app/views/shared/_sub-header.html.haml
.sub-header
  .single-container
    %header.single-header
      %h1
        = link_to root_path do
          = image_tag('//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3856598694', alt: "mercari")