config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
  end
  root 'items#index'

  resources :items do
    member do
      get 'purchase', to: 'items#purchase'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
    collection do
      get 'search', to: 'items#search'
    end
  end
  resources :users do
    member do
      get 'profile', to: 'users#profile'
      get 'credit', to: 'users#credit'
      get 'logout', to: 'users#logout'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many_attached :images, dependent: :destroy
  has_one :like
  has_many :items_categories
  has_many :categories, through: :items_categories
  accepts_nested_attributes_for :items_categories, allow_destroy: true
  belongs_to :brand,optional: true
  belongs_to :user
  # 現状はコメント機能の実装を行わないため、コメントアウトしております
  # has_many :comments, dependent: :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_search

  def index
    @items = Item.all.order("id DESC").limit(4)
    @items2 = Item.all.order("id ASC").limit(4)
    @q = Item.ransack(params[:q])
    @search_items = @q.result(distinct: true)
  end

  def search
    @q = Item.search(search_params)
    @search_items = @q.result(distinct: true)
    @search_name = params[:q]['name_cont']
  end

  def new
    @item = Item.new
    @item.items_categories.build
  end

  def create
    @status = '出品中'
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      flash.now[:alert] = "入力されていない項目があります"
      render action: :new
    end
  end

  def destroy
    if @item.user_id == current_user.id
      @item.destroy
      redirect_to root_path
    end
  end

  def show
    @images = @item.images
    @goods = Like.where(status: "良い")
    @normals = Like.where(status: "普通")
    @bads = Like.where(status: "悪い")
    @category = @item.categories.first

    @q = Item.ransack(params[:q])
    @search_items = @q.result(distinct: true)
  end

  def edit
    @serect_category = @item.categories.first
    @price = @item.price
    @fee = ((@price * 1.1) - @item.price).round
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    end
  end

  def purchase
    @item = Item.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_card_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay
    @item = Item.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
      :amount => @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
      :customer => card.customer_id, #顧客ID
      :currency => 'jpy', #日本円
    )
    @item.status = '交渉中'
    @item.save
    redirect_to item_path(params[:id]) #トップ画面に移動
  end

  def done
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :discription, :item_condition, :delivery_fee, :shipping_rule, :prefecture_id, :shipping_date, :price,images:[],brand_attributes: [:id, :name], items_categories_attributes: [:id,:category_id],remove_images:[]).merge(user_id: current_user.id, status: @status)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search_params
    params.require(:q).permit(:name_cont,:price_gteq,:price_lteq,:item_condition_eq)
  end

  def set_search
    @q = Item.ransack(params[:q])
    @search_items = @q.result(distinct: true)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/address-form.html.haml
= render 'shared/sub-header'
.progress
  .progress-bar
    %ul
      %li.progressContents
        会員情報
        .progressContents__dotRed
        .progressContents__lineRight_red
      %li.progressContents
        電話番号認証
        .progressContents__dotRed
        .progressContents__lineLeft_red
        .progressContents__lineRight_red
      %li.progressContents
        お届け先住所入力
        .progressContents__dotRed
        .progressContents__lineLeft_red
        .progressContents__lineRight
      %li.progressContents
        支払い方法
        .progressContents__dotGray
        .progressContents__lineLeft
        .progressContents__lineRight
      %li.progressContents
        完了
        .progressContents__dotGray
        .progressContents__lineLeft

.address-main
  .address-title
    %a.form-title 住所入力
  .formGroup
    %label(for="zip_code") お名前
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="zip_code" placeholder="例）山田" class="input-default")
    %input(type="text" value="" name="zip_code" placeholder="例）彩" class="input-default")
  .formGroup
    %label(for="zip_code") お名前カナ
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="zip_code" placeholder="例）ヤマダ" class="input-default")
    %input(type="text" value="" name="zip_code" placeholder="例）アヤ" class="input-default")
  .formGroup
    %label(for="zip_code") 郵便番号
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="zip_code" placeholder="例）1234567" class="input-default")
  .formGroup
    %label(for="prefecture") 都道府県
    %span.form-arbitrary-required 必須
    .select-wrap
      = form_with(url: '#') do |f|
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name
        %i.fa.fa-chevron-down
  .formGroup
    %label(for="city") 市区町村
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="city" placeholder="例) 横浜市緑区" class="input-default")
  .formGroup
    %label(for="address1_label") 番地
    %span.form-arbitrary-required 必須
    %input(type="text" value="" name="address1" placeholder="例) 青山1−1−1" class="input-default")
  .formGroup
    %label(for="address2_label") 建物名
    %span.form-arbitrary-any 任意
    %input(type="text" value="" name="address2" placeholder="例) 柳ビル103" class="input-default")
  .formGroup
    %label(for="address2_label") 電話
    %span.form-arbitrary-any 任意
    %input(type="text" value="" name="address2" placeholder="例) 0901234567" class="input-default")
  .formGroup
    %button(type="submit" class="btn")次へ進む
= render 'shared/sub-footer'

app/views/items/confirmation.html.haml
.single-container
  = render 'shared/sub-header'
  .single-main
    .main-contents
      .main-contents__header
        %p 購入内容の確認
      .main-contents__buy
        .buy-content
          %h3.item-image
            = image_tag('http://kotonohanoana.com/wp-content/uploads/2015/09/004504a0ae99befc80567a1284d63dcb.jpg')
          %p.item-name
            アイウエオ
          .buy-form
            %p.price 
              %span ¥1000
              送料込み
            %li.point ポイントはありません
            .price-table
              %p.pay 支払金額
              %span ¥1000
            .submit
              %button{type:"submit", class:"btn-default"}
                %p 購入する
      .user-info
        .user-info__inner
          %h3 配送先
          .user-info-text
            %br 〒570-0016
            大阪府 枚方市 香里ヶ丘193789-1-8
            %br ふじた さき
          .user-info-fix
            = link_to "変更する", "https://www.mercari.com/jp/transaction/address/m75484476611/"
            %i.fa.fa-chevron-right
      .pay-method
        .pay-method__inner
          %h3 お支払い方法
          .inner-text
            ************6789
            %br 07 / 23
          .figure
            = image_tag('//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2399382397', alt:"VISA")
          .user-info-fix
            = link_to "変更する", "https://www.mercari.com/jp/transaction/select_card/m75484476611/"
            %i.fa.fa-chevron-right
= render 'shared/sub-footer'

app/views/items/credit-form.html.haml
= render 'shared/sub-header'
%header.address-header
  %nav.progress-bar.signup-bar
    .clearfix
      %li
        会員情報
        .active__dot_red
        .line-right-red
      %li
        電話番号認証
        .active__dot_red
        .line-left-red
        .line-right-red
      %li
        お届け先住所入力
        .active__dot_red
        .line-left-red
        .line-right-red
      %li.active
        支払い方法
        .active__dot_red
        .line-left-red
        .line-right
      %li
        完了
        .active__dot_gray
        .line-left

= render 'shared/credit_form'
= render 'shared/sub-footer'

app/views/items/doneRegistration.html.haml
= render 'shared/sub-header'
%header.address-header
  %nav.progress-bar.signup-bar
    .clearfix
      %li
        会員情報
        .active__dot_red
        .line-right-red
      %li
        電話番号認証
        .active__dot_red
        .line-left-red
        .line-right-red
      %li
        お届け先住所入力
        .active__dot_red
        .line-left-red
        .line-right-red
      %li
        支払い方法
        .active__dot_red
        .line-left-red
        .line-right-red
      %li.active
        完了
        .active__dot_red
        .line-left-red
.doneRegistration-main
  .doneRegistration-title
    %a.form-title 会員登録完了
  .formGroup
    .done-comment
      %p ありがとうございます。
      %br 会員登録が完了しました。
  .formGroup
    %button(type="submit" class="btn")メルカリをはじめる
= render 'shared/aside'
= render 'shared/sub-footer'

app/views/items/edit.html.haml
= render 'shared/sub-header'
.item-main
  .form
    = form_with(model:@item, local: true) do |f|
      .item-contents
        .item-contents__head
          .head__title
            %h2 商品の情報を入力
        .item-contents__image
          .image__head
            %h3 出品画像
            %span 必須
            %h5 最大１０枚までアップロードできます
          .image__box
            = f.label :images do
              #itemtext
                %p#itemtextP1 
                %p#itemtextP2 
              = f.file_field :images, multiple: true, class: 'hidden',onchange:"previewFiles()"
              .imageSelect
              #preview
                - i = 0
                - while i < @item.images.length
                  = image_tag @item.images[i]
                  - i += 1
        .item-contents__info
          .info__name
            %h4 商品名
            %span 必須
          .info__default
            = f.text_field :name, type:"text", placeholder:"商品名（必須４０文字まで）"
          .info__description
            .description__item
              %h4 商品の説明
              %span 必須
            .description__comment
              = f.text_area :discription, type:'text', placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",rows: "10",class: "textarea-default"
        #categoryAppend-size.item-contents__detail.edit
          %h4 商品の詳細
          .detail__box
            .box__group
              %label
                %h3 カテゴリー
                %span 必須
              #categoryAppend.select__box
                = fields_for :items_categories do |items_categories|
                  = items_categories.select :category_id,Category.roots.map {|i| ["#{i.name}", i.id]},{prompt: "---",selected:@item.categories.first.root.id},{id:"form1"}
                %i.fa.fa-chevron-down
              #categoryAppend-1.select__box
                = fields_for :items_categories do |items_categories|
                  = items_categories.select :category_id,@serect_category.root.children.map{|c|[c.name,c.id]},{prompt: "---",selected:@item.categories.first.parent.id},{id:"form2"}
                %i.fa.fa-chevron-down
              #categoryAppend-2.select__box
                = f.fields_for :items_categories do |items_categories|
                  = items_categories.select :category_id,@serect_category.siblings.map{|c|[c.name,c.id]},{prompt: "---"},{id:"form3"}
                %i.fa.fa-chevron-down
            #categoryAppend-sizeform.box__group1.hidden
              %label
                %h3 サイズ
                %span.any 任意
              .select__box
                = f.select :size, [["---","---"],["XXS以下","XXS以下"],["XS(SS)","XS(SS)"],["S","S"],["M","M"],["L","L"],["XL(LL)","XL(LL)"],["2XL(3L)","2XL(3L)"],["3XL(4L)","3XL(4L)"],["4XL(5L)以上","4XL(5L)以上"],["FREE SIZE","FREE SIZE"]], class:"select-default"
                %i.fa.fa-chevron-down
            #categoryAppend-any.box__group-any
              %label
                %h3 ブランド
                %span.any 任意
              .select__box
                = f.text_field :brand, class:"select-default", placeholder:"例）シャネル"
            .box__group1
              %h3 商品の状態
              %span 必須
              .select__box
                = f.select :item_condition, [["---","---"],["新品・未使用","新品・未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], class:"select-default"
                %i.fa.fa-chevron-down
        #a.item-contents__shipping
          %h4 配送について
          .form-question
            = link_to "？", "#", target: "_blank"
          .shipping__box
            .box__fee
              %h3 配送料の負担
              %span 必須  
              #fee.select__box
                = f.select :delivery_fee, [["---","---"],["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]], class:"select-default"
                %i.fa.fa-chevron-down
            #appendBox-rule.box__rule.hidden
              %h3 配送方法
              %span 必須  
              .select__box
                = f.select :shipping_rule, [["---","---"],["未定","未定"],["らくらくメルカリ便","らくらくメルカリ便"],["ゆうメール","ゆうメール"],["レターパック","レターパック"],["普通郵便(定型、定型外)","普通郵便(定型、定型外)"],["クロネコヤマト","クロネコヤマト"],["ゆうパック","ゆうパック"],["クリックポスト","クリックポスト"],["ゆうパケット","ゆうパケット"]], class:"select-default"
                %i.fa.fa-chevron-down
            .box__area
              %h3 発送元の地域
              %span 必須
              .select__box
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name
                %i.fa.fa-chevron-down
            .box__date
              %h3 発送までの日数
              %span 必須
              .select__box
                = f.select :shipping_date, [["---","---"],["１〜２日で発送","１〜２日で発送"],["２〜３日で発送","２〜３日で発送"],["４〜７日で発送","４〜７日で発送"]], class:"select-default"
                %i.fa.fa-chevron-down
        .item-contents__price
          %h4 販売価格(300〜9,999,999)
          .form-question
            = link_to "？", "#", target: "_blank"
          .price__box
            .list__top
              .top__left
                価格
                %span 必須
              .top__right
                .price__input
                  ￥
                  = f.text_field :price, type:"text", placeholder:"例）300", id: "price"
            .list__center
              .left
                販売手数料(10%)
                #fee-js
                  %p#fee-
                    ¥
                    = @fee
            .list__bottom
              %p.left 販売利益
              #profit-js
                %p.right#fee-
                  ¥
                  = @price - @fee
        .item-contents__submit
          = link_to "禁止されている商品", "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
          = link_to "行為", "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
          を必ずご確認ください。
          %br またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to "偽ブランドの販売", "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
          は犯罪であり処罰される可能性があります。
          %br また、出品を持ちまして
          = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/"
          にも同意したことになります。
          %br
          .submit__buttom
            = f.submit '出品する', class: 'btn-default'
          .submit__last
            = link_to root_path do
              %button{type:"submit", class:"btn-default"}
                もどる
= render 'shared/sub-footer'

app/views/items/index.html.haml
.wrapper

  = render 'shared/header'

  = render 'shared/main'

  = render 'shared/aside'

  = render 'shared/footer'

  = render 'shared/footer-btn'

app/views/items/new.html.haml
= render 'shared/item'

app/views/items/phone.html.haml
%body
  .phone
    %header.single-header
      %h1
        = link_to "https://www.mercari.com/jp/" do
          = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2399382397",alt: "mercari")
      %nav.progress-bar.signup-bar
        .clearfix
          %li
            会員情報
            .active__dot_red
            .line-right-red
          %li.active
            電話番号認証
            .active__dot_red
            .line-left-red
            .line-right
          %li
            お届け先住所入力
            .active__dot_gray
            .line-left
            .line-right
          %li
            支払い方法
            .active__dot_gray
            .line-left
            .line-right
          %li
            完了
            .active__dot_gray
            .line-left
    %main.single-main
    %section.l-single-container
      %h2.l-chapter-head 電話番号の確認
      %form.l-single-inner{action: "https://www.mercari.com/jp/signup/sms_confirmation/sms/", :method => "POST", :novalidate => "novalidate"}
        %input{name: "after_save_callback", type: "hidden", value: ""}/
        .l-single-content
          .form-group
            %label{for: "phone_number"} 携帯電話の番号
            %input.phone-form{name: "phone_number", placeholder: "携帯電話の番号を入力", type: "tel", value: ""}/
          %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          %button.sms-send.btn-red{type: "submit"} SMSを送信する
          %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .form-group.text-right
            = link_to "/jp/help_center/article/244/", target: "_blank" do
              電話番号の確認が必要な理由
              %i.icon-arrow-right
          %input{name: "__csrf_value", type: "hidden", value: "6e96973f6b27a207edf3292b08d8fd656e32ae534791cd3dc241ee87dd8df1be1acfe54eeff9d13745f774fde996dd8f53317f28432f8170a3f3043d49f78242e"}/
          %input{name: "id", type: "hidden", value: "745713821"}/
= render 'shared/sub-footer'

app/views/items/show.html.haml
.wrapper

  = render 'shared/header'

  .bread-crumbs
    %ul
      %li
      - breadcrumb :item, @item
      = breadcrumbs separator: " #{content_tag(:i, '', class:'fa fa-chevron-right')} "
  .item-box-container
    .item-name
      = @item.name
    .item-main-content.clearfix
      .photo
        -# スライダー機能は後で実装します
        .photo__slider
          .slider__inner
            = image_tag @item.images.first, class: "inner_img"
            .itemList
              - i = 0
              - while i < @item.images.length
                = image_tag @item.images[i]
                - i += 1
        .photo__soldout-budge
          - if @item.status == '交渉中'
            .budge-text SOLD
            .budge-layout

      %table{border: "5",rules: "all",class: "detail-table"}
        %tbody
          %tr
            %th 出品者
            %td
              = link_to "#", class: "buyer-name" do
                = @item.user.nickname
              .user-ratings__good
                = fa_icon 'laugh',class: 'icon-good'
                %span
                  = @goods.count
              .user-ratings__normal
                = fa_icon 'meh',class: 'icon-normal'
                %span
                  = @normals.count
              .user-ratings__bad
                = fa_icon 'frown',class: 'icon-bad'
                %span 
                  = @bads.count
          %tr
            %th カテゴリー
            %td
              = link_to "#", class: "category-name" do
                = @category.root.name
              = link_to "#", class: "category-name__child" do
                = fa_icon 'chevron-right',class: 'icon-arrow-right'
                = @category.parent.name
              = link_to "#", class: "category-name__child" do
                = fa_icon 'chevron-right',class: 'icon-arrow-right'
                = @category.name
          %tr
            %th ブランド
            %td
              = link_to "#", class: "brand-name" do
                = @item.brand_id
          %tr
            %th 商品の状態
            %td
              = @item.item_condition
          %tr
            %th 配送料の負担
            %td
              = @item.delivery_fee
          %tr
            %th 配送の方法
            %td
              = @item.shipping_rule
          %tr
            %th 配送元地域
            %td 
              = link_to "#", class: "area-name" do
                = @item.prefecture.name
          %tr
            %th 発送日の目安
            %td
              = @item.shipping_date

    .price-box
      %span.price-box__price
        ¥
        = @item.price
      %span.price-box__tax  (税込)
      %span.price-box__shipping-fee 送料込み

    .buy-btn
      - if @item.status == '出品中' && @item.user_id != current_user.id
        = link_to purchase_item_path, class: 'purchase-btn' do
          購入する
      - elsif @item.status == '出品中' && @item.user_id == current_user.id
      - else @item.status == '交渉中'
        %button{type:"submit", class:"sold-btn"}
          %p 売り切れました
    .description
      %p.description__inner
        ■商品ご覧頂き、誠にありがとうございます。
        = @item.discription

    .btns.clearfix
      .btns__left
        %button.like-btn
          = fa_icon 'heart',class: 'icon-heart'
          %span.like-btn__title いいね!
          %span.like-btn__num 7
        %button.report-btn
          =fa_icon 'flag',class: 'icon-flag'
          %span.report-btn__title 不適切な商品の報告

      .btns__right
        = link_to "#" do
          = fa_icon 'lock',class: 'icon-lock'
          %span あんしん・あんぜんへの取り組み

  .item-comments
    .comments-container
      .comments-box
        %ul.comments-box__comments
          %li.commment.clearfix
            .comment__user
              = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/user-icon.svg?2399382397",class: "user-unknown")
              %figcaption.bold アワチン
            .comment__body
              .comment-body__text ぜひ買いたいです！
              .comment-body__icons.clearfix
                .icon-left
                  = fa_icon 'clock',class: 'icon-clock'
                  %span 215日前
                .icon-right
                  = link_to "#" do
                    = fa_icon 'flag',class: 'icon-flag'
              =fa_icon 'caret-left',class: 'icon-arrow-left'

          %li.commment.clearfix
            .comment__user
              = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/user-icon.svg?2399382397",class: "user-unknown")
              %figcaption.bold  ノブタカ
            .comment__body
              .comment-body__text いいね！
              .comment-body__icons.clearfix
                .icon-left
                  = fa_icon 'clock',class: 'icon-clock'
                  %span 215日前
                .icon-right
                  = link_to "#" do
                    = fa_icon 'flag',class: 'icon-flag'
              = fa_icon 'caret-left',class: 'icon-arrow-left'

      .comments-box
        .comment-form
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = form_with url: "#", class: "comment-form" do |f|
            = f.text_area :comment, class: "comment-form__text_area"
            = f.submit "コメントする", class: "comment-form__submit"

  %ul.link-prev-next.clearfix
    %li.prev
      = link_to '#' do
        = fa_icon 'chevron-left',class: 'icon-arrow-left'
        ディズニーヴィランズ 2個セット バッジ バッチ Villains 2018
    %li.next
      = link_to '#' do
        = fa_icon 'chevron-right',class: 'icon-arrow-right'
        楽天パンダ ノート&マスキングテープセット

  .item-social-media-box
    .item-delete-edit
    - if user_signed_in? && current_user.id == @item.user_id
      = link_to item_path(@item.id), method: :delete do
        削除する
        
    - if user_signed_in? && current_user.id == @item.user_id 
      = link_to edit_item_path(@item.id) do
        編集する

  .items-in-user-profile
    .item-box-container.clearfix
      .item-box-container__head
        = link_to '#' do
          BOON90sリバイバル@フォロー割さんのその他の出品
      .item-box-container__content
        .item-box-left
          = link_to "#" do
            .photo
              = image_tag("https://static.mercdn.net/thumb/photos/m33132342381_1.jpg?1559204933",class: "photo__img")
            .item
              .item__name LOEWE ロエベ ハンドバッグ レザー
              .item__num
                .item__price ¥ 14,000
              .item__tax (税込)
        .item-box
          = link_to "#" do
            .photo
              = image_tag("https://static.mercdn.net/thumb/photos/m33132342381_1.jpg?1559204933",class: "photo__img")
            .item
              .item__name LOEWE ロエベ ハンドバッグ レザー
              .item__num
                .item__price ¥ 14,000
              .item__tax (税込)
        .item-box
          = link_to "#" do
            .photo
              = image_tag("https://static.mercdn.net/thumb/photos/m33132342381_1.jpg?1559204933",class: "photo__img")

            .item
              .item__name LOEWE ロエベ ハンドバッグ レザー
              .item__num
                .item__price ¥ 14,000
              .item__tax (税込)

    .item-box-container.clearfix
      .item-box-container__head
        = link_to '#' do
          コーチのショルダーバッグその他の出品
      .item-box-container__content
        .item-box-left
          = link_to "#" do
            .photo
              = image_tag("https://static.mercdn.net/thumb/photos/m33132342381_1.jpg?1559204933",class: "photo__img")
            .item
              .item__name LOEWE ロエベ ハンドバッグ レザー
              .item__num
                .item__price ¥ 14,000
              .item__tax (税込)
        .item-box
          = link_to "#" do
            .photo
              = image_tag("https://static.mercdn.net/thumb/photos/m33132342381_1.jpg?1559204933",class: "photo__img")
            .item
              .item__name LOEWE ロエベ ハンドバッグ レザー
              .item__num
                .item__price ¥ 14,000
              .item__tax (税込)
        .item-box
          = link_to "#" do
            .photo
              = image_tag("https://static.mercdn.net/thumb/photos/m33132342381_1.jpg?1559204933",class: "photo__img")
            .item
              .item__name LOEWE ロエベ ハンドバッグ レザー
              .item__num
                .item__price ¥ 14,000
              .item__tax (税込)

  = render 'shared/aside'

  = render 'shared/footer'