config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
  end
  root 'items#index'

  resources :items do
    member do
      get 'purchase', to: 'items#purchase'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
    collection do
      get 'search', to: 'items#search'
    end
  end
  resources :users do
    member do
      get 'profile', to: 'users#profile'
      get 'credit', to: 'users#credit'
      get 'logout', to: 'users#logout'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_index_path if card.exists?

    @q = Item.ransack(params[:q])
    @search_items = @q.result(distinct: true)
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
        description: '登録テスト', #なくてもOK
        email: current_user.email, #なくてもOK
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_index_path
      else
        redirect_to pay_card_index_path
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to new_card_path
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    @q = Item.ransack(params[:q])
    @search_items = @q.result(distinct: true)

    card = Card.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    else
      redirect_to new_card_path 
    end
  end
end

app/views/card/new.html.haml
= render 'shared/header'
.bread-crumbs
  %ul
    %li
    -# 修正が必要
    - breadcrumb :credit
    = breadcrumbs separator: " #{content_tag(:i, '', class:'fa fa-chevron-right')} "
.credit
  = render 'shared/side_bar'

  = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
    .mypage-pay-main
      .mypage-address-title
        %a.mypage-form-title クレジットカード情報入力
      .pay-box
        .mypage-formGroup-first
          %label カード番号
          %span.mypage-form-arbitrary-required 必須
          = text_field_tag "number", "", class: "mypage-input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %ul.mypage-signup-card-list
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3270184656", width: "49", height: "20")
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3270184656", width: "34", height: "20")
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3270184656", width: "30", height: "20")
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3270184656", width: "32", height: "20")
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3270184656", width: "21", height: "20")
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3270184656", width: "32", height: "20")
            %li.mypage-card-decoration
              = image_tag(src="//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3270184656", width: "32", height: "20")
        .mypage-formGroup-select
          %label.payment_card_expire 有効期限
          %span.mypage-form-arbitrary-required 必須
          %br
          .select-wrap
            %select#exp_month{name: "exp_month", type: "text", class: "mypage-select-default"}
              %option{value: "1"} 01
              %option{value: "2"} 02
              %option{value: "3"} 03
              %option{value: "4"} 04
              %option{value: "5"} 05
              %option{value: "6"} 06
              %option{value: "7"} 07
              %option{value: "8"} 08
              %option{value: "9"} 09
              %option{value: "10"} 10
              %option{value: "11"} 11
              %option{value: "12"} 12
            %i.fa.fa-chevron-down.credit-mypage
          %span.mypage-credit-selectbox 月
          %br
          .select-wrap
            %select#exp_year{name: "exp_year", type: "text", class: "mypage-select-default"}
              %option{value: "2019"} 19
              %option{value: "2020"} 20
              %option{value: "2021"} 21
              %option{value: "2022"} 22
              %option{value: "2023"} 23
              %option{value: "2024"} 24
              %option{value: "2025"} 25
              %option{value: "2026"} 26
              %option{value: "2027"} 27
              %option{value: "2028"} 28
              %option{value: "2029"} 29
            %i.fa.fa-chevron-down.credit-mypage
          %span.mypage-credit-selectbox 年
        .mypage-formGroup
          %label セキュリティコード
          %span.mypage-form-arbitrary-required 必須
          = text_field_tag "cvc", "", class: "mypage-input-default", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
          .mypage-card-text_box
            .mypage-card-text
              %span.mypage-questionForm ?
              カード裏面の番号とは？
              %i.icon-arrow-right
        #card_token
        = submit_tag "追加する", id: "token_submit", class: "mypage-creditbtn"

= render 'shared/aside'
= render 'shared/footer'
= render 'shared/footer-btn'

app/views/card/show.html.haml
= render 'shared/header'
.bread-crumbs
  %ul
    %li
    -# 修正が必要
    - breadcrumb :credit
    = breadcrumbs separator: " #{content_tag(:i, '', class:'fa fa-chevron-right')} "
.credit
  = render 'shared/side_bar'

  .mypage-pay-main
    .mypage-address-title
      %a.mypage-form-title 登録クレジットカード情報
    .pay-box
      .mypage-formGroup-first
        %label カード番号
        %br
        = "**** **** **** " + @default_card_information.last4
        %br
        %br
        %label 有効期限
        %br
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        %br
        %br
        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class: "mypage-deletebtn") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する

= render 'shared/aside'
= render 'shared/footer'
= render 'shared/footer-btn'